export const types = {
  RESET_ALL_AUTH_REDUCER: 'RESET_ALL_AUTH_REDUCER',
  USER_LOGIN: 'USER_LOGIN',

  //User
  RESET_ALL_USER_REDUCER: 'RESET_ALL_USER_REDUCER',
  GET_ALL_USER: 'GET_ALL_USER',

  //Absents
  RESET_ALL_ABSENT_REDUCER: 'RESET_ALL_ABSENT_REDUCER',
  GET_ALL_ABSENTS: 'GET_ALL_ABSENTS',
  DELETE_USER: 'DELETE_USER',
  REGISTER_USER: 'REGISTER_USER',

  //Reimbursement
  REIMBURSEMENT_RESET_REDUCER: 'REIMBURSEMENT_RESET_REDUCER',
  GET_ALL_REIMBURSEMENT: 'GET_ALL_REIMBURSEMENT',
  GET_BYID_REIMBURSEMENT: 'GET_BYID_REIMBURSEMENT',
  PAY_REIMBURSEMENT: 'PAY_REIMBURSEMENT',

  //Attendance Tag
  GET_ALL_ATTENDANCE_TAG: 'GET_ALL_ATTENDANCE_TAG',
  ADD_ATTENDANCE_TAG: 'ADD_ATTENDANCE_TAG',
  DELETE_ATTENDANCE_TAG: 'DELETE_ATTENDANCE_TAG',

  //Kas
  KAS_RESET_REDUCER: 'KAS_RESET_REDUCER',
  GET_ALL_KAS: 'GET_ALL_KAS',
}